name = "CamparyBindings"
uuid = "e7fadfd6-6fcd-4635-ad20-c2358ff7ed32"
authors = ["Isaia Nisoli"]
version = "0.1.0"

[deps]
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"

[compat]
julia = "1.4.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
